[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc = "0.8.34"
evm_version = "paris"
optimizer = true
optimizer_runs = 1000
offline = true

remappings = [
  "@forge-std/=lib/forge-std/src/",
  "ds-test/=lib/forge-std/lib/ds-test/src/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

fs_permissions = [
  { access = "read-write", path = "./deployments" },
  { access = "read-write", path = "./broadcast" }
]

[profile.ci]
offline = false

[fmt]
ignore=["lib/**"]
tab_width = 4
line_length = 120
bracket_spacing = true
int_types = "long"
quote_style = "double"
wrap_comments = true
number_underscore = "thousands"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
