export const VIGILIA_ESCROW_ABI = [
  // ─── State Variables ────────────────────────────────────────────────────────
  {
    name: "nextTaskId",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "nextSubmissionId",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "verifier",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    name: "tasks",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "taskId", type: "uint256" }],
    outputs: [
      { name: "client", type: "address" },
      { name: "contractor", type: "address" },
      { name: "resolver", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "fundedAmount", type: "uint256" },
      { name: "activeSubmissionId", type: "uint256" },
      { name: "submissionCount", type: "uint256" },
      { name: "state", type: "uint8" },
      { name: "stateBeforeDispute", type: "uint8" },
      { name: "requirementsURI", type: "string" },
      { name: "reviewWindow", type: "uint64" },
      { name: "verificationTimeout", type: "uint64" },
    ],
  },
  {
    name: "taskClaimPolicies",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "taskId", type: "uint256" }],
    outputs: [{ name: "", type: "uint8" }],
  },
  {
    name: "submissions",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "submissionId", type: "uint256" }],
    outputs: [
      { name: "taskId", type: "uint256" },
      { name: "submitter", type: "address" },
      { name: "evidenceURI", type: "string" },
      { name: "evidenceHash", type: "bytes32" },
      { name: "requestId", type: "bytes32" },
      { name: "verdict", type: "uint8" },
      { name: "submittedAt", type: "uint64" },
      { name: "verifiedAt", type: "uint64" },
    ],
  },
  {
    name: "pendingWithdrawals",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },

  // ─── Write Functions ─────────────────────────────────────────────────────────
  {
    name: "createTask",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "_contractor", type: "address" },
      { name: "_resolver", type: "address" },
      { name: "_amount", type: "uint256" },
      { name: "_reviewWindow", type: "uint64" },
      { name: "_requirementsURI", type: "string" },
    ],
    outputs: [{ name: "taskId", type: "uint256" }],
  },
  {
    name: "createTaskWithPolicy",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "_contractor", type: "address" },
      { name: "_resolver", type: "address" },
      { name: "_amount", type: "uint256" },
      { name: "_reviewWindow", type: "uint64" },
      { name: "_requirementsURI", type: "string" },
      { name: "_claimPolicy", type: "uint8" },
    ],
    outputs: [{ name: "taskId", type: "uint256" }],
  },
  {
    name: "createTaskWithPolicyAndTimeout",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "_contractor", type: "address" },
      { name: "_resolver", type: "address" },
      { name: "_amount", type: "uint256" },
      { name: "_reviewWindow", type: "uint64" },
      { name: "_requirementsURI", type: "string" },
      { name: "_claimPolicy", type: "uint8" },
      { name: "_verificationTimeout", type: "uint64" },
    ],
    outputs: [{ name: "taskId", type: "uint256" }],
  },
  {
    name: "fundTask",
    type: "function",
    stateMutability: "payable",
    inputs: [{ name: "_taskId", type: "uint256" }],
    outputs: [],
  },
  {
    name: "submitWork",
    type: "function",
    stateMutability: "payable",
    inputs: [
      { name: "_taskId", type: "uint256" },
      { name: "_evidenceURI", type: "string" },
      { name: "_evidenceHash", type: "bytes32" },
    ],
    outputs: [
      { name: "submissionId", type: "uint256" },
      { name: "requestId", type: "bytes32" },
    ],
  },
  {
    name: "approveTask",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "_taskId", type: "uint256" }],
    outputs: [],
  },
  {
    name: "claim",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "_taskId", type: "uint256" }],
    outputs: [],
  },
  {
    name: "claimTo",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "_taskId", type: "uint256" },
      { name: "_recipient", type: "address" },
    ],
    outputs: [],
  },
  {
    name: "markVerificationTimedOut",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "_taskId", type: "uint256" }],
    outputs: [],
  },
  {
    name: "raiseDispute",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "_taskId", type: "uint256" },
      { name: "_reasonURI", type: "string" },
    ],
    outputs: [],
  },
  {
    name: "resolveDispute",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "_taskId", type: "uint256" },
      { name: "_clientRefund", type: "uint256" },
      { name: "_contractorAward", type: "uint256" },
      { name: "_resolutionURI", type: "string" },
    ],
    outputs: [],
  },
  {
    name: "withdrawPending",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "withdrawPendingTo",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "_recipient", type: "address" }],
    outputs: [],
  },
  {
    name: "cancelTask",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "_taskId", type: "uint256" }],
    outputs: [],
  },
  {
    name: "retryVerification",
    type: "function",
    stateMutability: "payable",
    inputs: [{ name: "_taskId", type: "uint256" }],
    outputs: [{ name: "requestId", type: "bytes32" }],
  },

  // ─── Events ──────────────────────────────────────────────────────────────────
  {
    name: "TaskCreated",
    type: "event",
    inputs: [
      { name: "taskId", type: "uint256", indexed: true },
      { name: "client", type: "address", indexed: true },
      { name: "contractor", type: "address", indexed: true },
      { name: "resolver", type: "address", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
      { name: "reviewWindow", type: "uint64", indexed: false },
      { name: "verificationTimeout", type: "uint64", indexed: false },
      { name: "claimPolicy", type: "uint8", indexed: false },
      { name: "requirementsURI", type: "string", indexed: false },
    ],
  },
  {
    name: "TaskFunded",
    type: "event",
    inputs: [
      { name: "taskId", type: "uint256", indexed: true },
      { name: "client", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    name: "WorkSubmitted",
    type: "event",
    inputs: [
      { name: "taskId", type: "uint256", indexed: true },
      { name: "submissionId", type: "uint256", indexed: true },
      { name: "submitter", type: "address", indexed: true },
      { name: "evidenceURI", type: "string", indexed: false },
      { name: "evidenceHash", type: "bytes32", indexed: false },
      { name: "requestId", type: "bytes32", indexed: false },
    ],
  },
  {
    name: "VerdictRecorded",
    type: "event",
    inputs: [
      { name: "taskId", type: "uint256", indexed: true },
      { name: "submissionId", type: "uint256", indexed: true },
      { name: "verdict", type: "uint8", indexed: false },
      { name: "requestId", type: "bytes32", indexed: false },
      { name: "verifierNotesURI", type: "string", indexed: false },
    ],
  },
  {
    name: "VerificationFailedRecorded",
    type: "event",
    inputs: [
      { name: "taskId", type: "uint256", indexed: true },
      { name: "submissionId", type: "uint256", indexed: true },
      { name: "requestId", type: "bytes32", indexed: false },
      { name: "failureNotesURI", type: "string", indexed: false },
    ],
  },
  {
    name: "VerificationTimedOut",
    type: "event",
    inputs: [
      { name: "taskId", type: "uint256", indexed: true },
      { name: "submissionId", type: "uint256", indexed: true },
      { name: "requestId", type: "bytes32", indexed: true },
      { name: "timeoutAt", type: "uint64", indexed: false },
    ],
  },
  {
    name: "VerificationRetried",
    type: "event",
    inputs: [
      { name: "taskId", type: "uint256", indexed: true },
      { name: "submissionId", type: "uint256", indexed: true },
      { name: "payer", type: "address", indexed: true },
      { name: "requestId", type: "bytes32", indexed: false },
    ],
  },
  {
    name: "TaskApproved",
    type: "event",
    inputs: [
      { name: "taskId", type: "uint256", indexed: true },
      { name: "client", type: "address", indexed: true },
      { name: "submissionId", type: "uint256", indexed: true },
    ],
  },
  {
    name: "TaskClaimed",
    type: "event",
    inputs: [
      { name: "taskId", type: "uint256", indexed: true },
      { name: "recipient", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    name: "DisputeRaised",
    type: "event",
    inputs: [
      { name: "taskId", type: "uint256", indexed: true },
      { name: "raisedBy", type: "address", indexed: true },
      { name: "previousState", type: "uint8", indexed: false },
      { name: "reasonURI", type: "string", indexed: false },
    ],
  },
  {
    name: "DisputeResolved",
    type: "event",
    inputs: [
      { name: "taskId", type: "uint256", indexed: true },
      { name: "resolver", type: "address", indexed: true },
      { name: "clientRefund", type: "uint256", indexed: false },
      { name: "contractorAward", type: "uint256", indexed: false },
      { name: "resolutionURI", type: "string", indexed: false },
    ],
  },
  {
    name: "TaskCancelled",
    type: "event",
    inputs: [
      { name: "taskId", type: "uint256", indexed: true },
      { name: "client", type: "address", indexed: true },
      { name: "refundAmount", type: "uint256", indexed: false },
    ],
  },
  {
    name: "PendingWithdrawalClaimed",
    type: "event",
    inputs: [
      { name: "account", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
] as const;

// ─── VigiliaGrantRound ABI (v0.4) ────────────────────────────────────────────
export const VIGILIA_GRANT_ROUND_ABI = [
  // ─── State Variables ────────────────────────────────────────────────────────
  {
    name: "nextRoundId",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "nextApplicationId",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "verifier",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    name: "rounds",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "roundId", type: "uint256" }],
    outputs: [
      { name: "sponsor", type: "address" },
      { name: "judge", type: "address" },
      { name: "prizeAmount", type: "uint256" },
      { name: "maxWinners", type: "uint256" },
      { name: "totalFunded", type: "uint256" },
      { name: "selectedCount", type: "uint256" },
      { name: "claimedCount", type: "uint256" },
      { name: "totalClaimed", type: "uint256" },
      { name: "totalRefunded", type: "uint256" },
      { name: "applicationsCount", type: "uint256" },
      { name: "applicationDeadline", type: "uint64" },
      { name: "reviewDeadline", type: "uint64" },
      { name: "requirementsURI", type: "string" },
      { name: "screeningMode", type: "uint8" },
      { name: "state", type: "uint8" },
    ],
  },
  {
    name: "applications",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "applicationId", type: "uint256" }],
    outputs: [
      { name: "roundId", type: "uint256" },
      { name: "applicant", type: "address" },
      { name: "evidenceURI", type: "string" },
      { name: "evidenceHash", type: "bytes32" },
      { name: "requestId", type: "bytes32" },
      { name: "verdict", type: "uint8" },
      { name: "status", type: "uint8" },
      { name: "selected", type: "bool" },
      { name: "claimed", type: "bool" },
      { name: "submittedAt", type: "uint64" },
      { name: "reviewedAt", type: "uint64" },
      { name: "notesURI", type: "string" },
    ],
  },
  {
    name: "applicationOf",
    type: "function",
    stateMutability: "view",
    inputs: [
      { name: "roundId", type: "uint256" },
      { name: "applicant", type: "address" },
    ],
    outputs: [{ name: "applicationId", type: "uint256" }],
  },
  {
    name: "pendingWithdrawals",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "getRoundApplications",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "roundId", type: "uint256" }],
    outputs: [{ name: "applicationIds", type: "uint256[]" }],
  },
  {
    name: "requiredFunding",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "roundId", type: "uint256" }],
    outputs: [{ name: "amount", type: "uint256" }],
  },
  {
    name: "canSelectApplication",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "applicationId", type: "uint256" }],
    outputs: [{ name: "eligible", type: "bool" }],
  },
  {
    name: "unallocatedAmount",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "roundId", type: "uint256" }],
    outputs: [{ name: "amount", type: "uint256" }],
  },
  {
    name: "selectedAllocation",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "roundId", type: "uint256" }],
    outputs: [{ name: "amount", type: "uint256" }],
  },

  // ─── Write Functions ─────────────────────────────────────────────────────────
  {
    name: "createRound",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "_judge", type: "address" },
      { name: "_prizeAmount", type: "uint256" },
      { name: "_maxWinners", type: "uint256" },
      { name: "_applicationDeadline", type: "uint64" },
      { name: "_reviewDeadline", type: "uint64" },
      { name: "_requirementsURI", type: "string" },
      { name: "_screeningMode", type: "uint8" },
    ],
    outputs: [{ name: "roundId", type: "uint256" }],
  },
  {
    name: "fundRound",
    type: "function",
    stateMutability: "payable",
    inputs: [{ name: "_roundId", type: "uint256" }],
    outputs: [],
  },
  {
    name: "submitApplication",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "_roundId", type: "uint256" },
      { name: "_evidenceURI", type: "string" },
      { name: "_evidenceHash", type: "bytes32" },
    ],
    outputs: [{ name: "applicationId", type: "uint256" }],
  },
  {
    name: "requestApplicationScreening",
    type: "function",
    stateMutability: "payable",
    inputs: [{ name: "_applicationId", type: "uint256" }],
    outputs: [{ name: "requestId", type: "bytes32" }],
  },
  {
    name: "recordManualScreening",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "_applicationId", type: "uint256" },
      { name: "_verdict", type: "uint8" },
      { name: "_notesURI", type: "string" },
    ],
    outputs: [],
  },
  {
    name: "selectFinalists",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "_roundId", type: "uint256" },
      { name: "_applicationIds", type: "uint256[]" },
    ],
    outputs: [],
  },
  {
    name: "rejectApplication",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "_applicationId", type: "uint256" },
      { name: "_reasonURI", type: "string" },
    ],
    outputs: [],
  },
  {
    name: "finalizeRound",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "_roundId", type: "uint256" }],
    outputs: [],
  },
  {
    name: "claimPrize",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "_applicationId", type: "uint256" }],
    outputs: [],
  },
  {
    name: "refundUnallocated",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "_roundId", type: "uint256" }],
    outputs: [{ name: "refundAmount", type: "uint256" }],
  },
  {
    name: "cancelRound",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "_roundId", type: "uint256" }],
    outputs: [],
  },
  {
    name: "withdrawPending",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },

  // ─── Events ──────────────────────────────────────────────────────────────────
  {
    name: "RoundCreated",
    type: "event",
    inputs: [
      { name: "roundId", type: "uint256", indexed: true },
      { name: "sponsor", type: "address", indexed: true },
      { name: "judge", type: "address", indexed: true },
      { name: "prizeAmount", type: "uint256", indexed: false },
      { name: "maxWinners", type: "uint256", indexed: false },
      { name: "applicationDeadline", type: "uint64", indexed: false },
      { name: "reviewDeadline", type: "uint64", indexed: false },
      { name: "requirementsURI", type: "string", indexed: false },
      { name: "screeningMode", type: "uint8", indexed: false },
    ],
  },
  {
    name: "RoundFunded",
    type: "event",
    inputs: [
      { name: "roundId", type: "uint256", indexed: true },
      { name: "sponsor", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    name: "ApplicationSubmitted",
    type: "event",
    inputs: [
      { name: "roundId", type: "uint256", indexed: true },
      { name: "applicationId", type: "uint256", indexed: true },
      { name: "applicant", type: "address", indexed: true },
      { name: "evidenceURI", type: "string", indexed: false },
      { name: "evidenceHash", type: "bytes32", indexed: false },
    ],
  },
  {
    name: "ApplicationScreeningRequested",
    type: "event",
    inputs: [
      { name: "roundId", type: "uint256", indexed: true },
      { name: "applicationId", type: "uint256", indexed: true },
      { name: "payer", type: "address", indexed: true },
      { name: "requestId", type: "bytes32", indexed: false },
    ],
  },
  {
    name: "ApplicationVerdictRecorded",
    type: "event",
    inputs: [
      { name: "roundId", type: "uint256", indexed: true },
      { name: "applicationId", type: "uint256", indexed: true },
      { name: "verdict", type: "uint8", indexed: false },
      { name: "notesURI", type: "string", indexed: false },
    ],
  },
  {
    name: "ApplicationVerificationFailed",
    type: "event",
    inputs: [
      { name: "roundId", type: "uint256", indexed: true },
      { name: "applicationId", type: "uint256", indexed: true },
      { name: "requestId", type: "bytes32", indexed: false },
      { name: "notesURI", type: "string", indexed: false },
    ],
  },
  {
    name: "FinalistSelected",
    type: "event",
    inputs: [
      { name: "roundId", type: "uint256", indexed: true },
      { name: "applicationId", type: "uint256", indexed: true },
      { name: "applicant", type: "address", indexed: true },
    ],
  },
  {
    name: "ApplicationRejected",
    type: "event",
    inputs: [
      { name: "roundId", type: "uint256", indexed: true },
      { name: "applicationId", type: "uint256", indexed: true },
      { name: "reasonURI", type: "string", indexed: false },
    ],
  },
  {
    name: "RoundFinalized",
    type: "event",
    inputs: [
      { name: "roundId", type: "uint256", indexed: true },
      { name: "selectedCount", type: "uint256", indexed: false },
    ],
  },
  {
    name: "PrizeClaimed",
    type: "event",
    inputs: [
      { name: "roundId", type: "uint256", indexed: true },
      { name: "applicationId", type: "uint256", indexed: true },
      { name: "applicant", type: "address", indexed: true },
      { name: "recipient", type: "address", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    name: "UnallocatedRefundCredited",
    type: "event",
    inputs: [
      { name: "roundId", type: "uint256", indexed: true },
      { name: "sponsor", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    name: "RoundCancelled",
    type: "event",
    inputs: [
      { name: "roundId", type: "uint256", indexed: true },
      { name: "refundAmount", type: "uint256", indexed: false },
    ],
  },
  {
    name: "PendingWithdrawalClaimed",
    type: "event",
    inputs: [
      { name: "account", type: "address", indexed: true },
      { name: "recipient", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
] as const;
