// SPDX-License-Identifier: MIT
pragma solidity 0.8.34;

import { IVigiliaVerifier } from "../interfaces/IVigiliaVerifier.sol";

/// @title MockVerifier
/// @notice Deterministic verifier mock for tests and local demos before Somnia Agent integration.
/// @dev This mock does not authenticate callers or execute external verification. It only returns deterministic request
/// IDs so the escrow state machine can be tested independently from Somnia Agent infrastructure.
contract MockVerifier is IVigiliaVerifier {
    /// @notice Emitted when a caller requests mock verification.
    /// @param requestId Deterministic request identifier returned to the caller.
    /// @param taskId Task identifier passed through by the caller.
    /// @param submissionId Submission identifier passed through by the caller.
    /// @param evidenceURI Public evidence URI passed through by the caller.
    event MockVerificationRequested(
        bytes32 indexed requestId, uint256 indexed taskId, uint256 indexed submissionId, string evidenceURI
    );

    /// @notice Monotonic nonce used to make request IDs unique.
    uint256 public nextRequestNonce;

    /// @notice Test switch that forces `requestVerification` to return `bytes32(0)`.
    /// @dev Used to verify escrow rollback behavior for invalid verifier responses.
    bool public forceZeroRequestId;

    /// @notice Tracks request IDs generated by this mock.
    mapping(bytes32 requestId => bool exists) public requests;

    /// @notice Configures whether the mock should return a zero request ID.
    /// @param _forceZeroRequestId True to return `bytes32(0)` from future requests.
    function setForceZeroRequestId(bool _forceZeroRequestId) external {
        forceZeroRequestId = _forceZeroRequestId;
    }

    /// @inheritdoc IVigiliaVerifier
    function requestVerification(uint256 _taskId, uint256 _submissionId, string calldata _evidenceURI)
        external
        payable
        returns (bytes32 requestId)
    {
        nextRequestNonce++;
        if (forceZeroRequestId) return bytes32(0);

        requestId = keccak256(abi.encode(msg.sender, _taskId, _submissionId, _evidenceURI, nextRequestNonce));
        requests[requestId] = true;

        emit MockVerificationRequested(requestId, _taskId, _submissionId, _evidenceURI);
    }
}
